# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python build and test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ^3.12
          
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4

    - name: Install dependencies
      run: poetry install

    - name: Cache venv
      uses: actions/cache@v4.0.2
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Test with pytest
      run: poetry run pytest
